### ISSUE TITLE
Where's the images resources

### ISSUE THREAD

**Issue by lawbyte** [4d4c/PWNgress#2]
There's missing file on images, like arrow and the others?
please update

**Comment by lawbyte** [comment]
and the settings file

**Comment by 4d4c** [comment]
I won't be sharing images - https://github.com/4d4c/PWNgress/blob/master/.gitignore#L3-L5. You can create your own and store them in /images folder. Same for fonts files.

Settings file should be created for each server separately - https://github.com/4d4c/PWNgress/blob/master/src/PWNgress.py#L920
